
### Add new role
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic max 123

{
    "username": "user2",
    "password": "123",
    "role": "USER"
}

### Get order
GET http://localhost:8080/orders
Content-Type: application/json
Authorization: Basic user 123

### Get order by id
GET http://localhost:8080/orders/id
Content-Type: application/json
Authorization: Basic user 123

### Add order
POST http://localhost:8080/orders
Content-Type: application/json
Authorization: Basic user 123

{
  "products": {
    "1": 2,
    "2": 3,
    "3": 3
  }
}

### Delete order by id
DELETE http://localhost:8080/orders/6
Content-Type: application/json
Authorization: Basic user 123


### Get order
GET http://localhost:8080/products
Content-Type: application/json
Authorization: Basic max 123

### Get order by id
GET http://localhost:8080/products/5
Content-Type: application/json
Authorization: Basic max 123


### Add product
POST http://localhost:8080/products
Content-Type: application/json
Authorization: Basic max 123

{
  "name": "milk",
  "price": 15.0
}

### Delete product by id
DELETE http://localhost:8080/products/5
Content-Type: application/json
Authorization: Basic max 123







